
services:
  wallet:
    build: .
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/wallet-api
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:8080/health-check || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
    networks:
      - wallet-network

  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=api
    ports:
      - '27017:27017'
    volumes:
      - ./mdb-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
    networks:
      - wallet-network

volumes:
  mdb-data:

networks:
  wallet-network:
    driver: bridge